### ISSUE TITLE
Auto-detect Intune Mode and Munki presence

### ISSUE THREAD

**Issue by dechkovanen** [macadmins/SupportCompanion#32]
The app could auto-detect some settings automatically if no configuration profile is present, this would ease up deployment in some scenarios.

I.e. the following:
- Intune Mode: if MSC is not installed and machine is enrolled in Intune (verify enrollment URL in MDM enrollment profile), Intune Mode would default to Enabled
- Hidden widgets: If MSC is not installed, hide all Munki-specific widgets and Evergreen info

**Comment by almenscorner** [comment]
This will be part of the Swift update currently in public preview
