### ISSUE TITLE
Run actions as logged in user

### ISSUE THREAD

**Issue by dechkovanen** [macadmins/SupportCompanion#33]
When setting custom actions, there could be a boolean value "Run as user" for each entry and defaults to False. Some utility command need to be executed as user, some as root so this would help setting up both.

**Comment by almenscorner** [comment]
The actions are running as the current user, currently in order to run a command as root you'd have to run it with `osascript` and specify `with administrator privileges` to prompt for authentication.

**Comment by almenscorner** [comment]
This will be part of the Swift update currently in public preview
