### ISSUE TITLE
Option for support companion as "more in depth"  for support app

### ISSUE THREAD

**Issue by hachirotahoshino** [macadmins/SupportCompanion#36]
For Quick support we use Support App and i think Support Companion could be a very good "More support..." option in support app.

from support app i can call an app, but it would be cool to have a key in the profile to tell the app not to have menubar icon and to be able to launch it as an independant application, opening the app would open directly supportcompanion main window?

**Comment by almenscorner** [comment]
Playing around with this I am able to get a URL Scheme working so the app can be started and shown using `open supportcompanion://home` for example, the thing that is not working by doing this is hiding and showing the window multiple times. This means that if the app were to be started from a URL, it would not continue to run in the background if the window is closed and therefor no notifications would be sent on a schedule.

If all you want is to show the window when the user wanted to and do not care about recurring notifications I guess it would be fine.

**Comment by hachirotahoshino** [comment]
it would be sufficient for this use i think, as we would use support companion for more in depth support if needed.

**Comment by almenscorner** [comment]
Okay so how about this, if the app is started using the URL, the tray menu will still show so you can add custom actions still and use them. But, if the window is closed when launched via URL, the app will exit instead of staying in the background

**Comment by hachirotahoshino** [comment]
that looks good enough 👌
