### ISSUE TITLE
Remove (or just make empty) unwanted tiles

### ISSUE THREAD

**Issue by hachirotahoshino** [macadmins/SupportCompanion#37]
being able to remove tiles or blank tiles which either are unwanted for end user, or which are not populated.

ie my evergreen tile is empty, better have nothing writed in it, i could have a key to tell hide tile evergreen and the form of the tile would appear but with no text?

**Comment by almenscorner** [comment]
Widgets can be hidden using the `HiddenWidgets` key already :)

**Comment by hachirotahoshino** [comment]
oh, thanks, my bad 😅 will test this asap

**Comment by almenscorner** [comment]
No worries, closing the issue :)
