### ISSUE TITLE
Multiple separators ignored in custom DesktopInfo

### ISSUE THREAD

**Issue by dechkovanen** [macadmins/SupportCompanion#47]
Only the second separator is shown in following configuration. Expectation would be two separators in specified locations.
```
<key>DesktopInfoCustomItems</key>
<array>
	<string>HostName</string>
	<string>SerialNumber</string>
	<string>Separator</string>
	<string>LastBootTime</string>
	<string>StorageInfo</string>
	<string>Separator</string>
	<string>SupportPhone</string>
	<string>SupportEmail</string>
</array>
```

**Comment by almenscorner** [comment]
You are right that the separator for now is a fixed separator and no additional ones can be added. I will look in to changing that behaviour so it's configureable in the custom view.
