### ISSUE TITLE
SupportCompanion Full Screen strange behaviour

### ISSUE THREAD

**Issue by MehdiYawari** [macadmins/SupportCompanion#53]
While setting the SupportCompanion to full screen, the edges of the screen turns black and the app is not really in full screen.
Then I have only the option to close/exit the app, which is then corrupt the whole desktop screen, meaning screen stays in black.
I think, it is enough to have the default screen size of the app as full screen (no full screen option). Or Full screen behavior must be fixed.
 
See the attached screenshots:
1: app in full screen
2: app closed but the screen stays black till support 

<img width="1440" alt="Screenshot 2024-11-20 at 16 44 32" src="https://github.com/user-attachments/assets/92861646-eabc-4b9a-87a8-2dbe6630cd5e">
<img width="1440" alt="Screenshot 2024-11-20 at 16 44 44" src="https://github.com/user-attachments/assets/749f2701-6db0-4515-80d7-c1d0b2babe74">

**Comment by almenscorner** [comment]
I was able to replicate this behaviour, but, as the project is being migrated to Swift soon and this issue will no longer exist I will target this to be fixed with the 2.0.0 update currently in public preview.
