### ISSUE TITLE
Desktop info not working properly

### ISSUE THREAD

**Issue by dechkovanen** [macadmins/SupportCompanion#57]
Desktop info is shown in bottom right instead of left, and hiding entire "Network Information" and "Storage" categories does not work. 

Version 2.0.0.80892 (2.0.0.80892).

Config snippet as follows - desktop info is shown and single items are hidden properly, so it works partially.

`			<key>ShowDesktopInfo</key>
			<true/>
			<key>DesktopInfoBackgroundColor</key>
			<string>#000000</string>
			<key>DesktopInfoBackgroundOpacity</key>
			<real>0.5</real>
			<key>DesktopInfoLevel</key>
			<integer>5</integer>
			<key>DesktopInfoHideItems</key>
			<array>
				<string>Model</string>
				<string>Processor</string>
				<string>Network Information</string>
				<string>Memory</string>
				<string>OSBuild</string>
				<string>OSVersion</string>
				<string>Storage</string>
			</array>
			<key>DesktopInfoFontSize</key>
			<integer>16</integer>
			<key>DesktopPosition</key>
			<string>BottomLeft</string>`

**Comment by dechkovanen** [comment]
Update: installed the release 2.0.1.80909 version which fixed the hiding issue but not the alignment issue.

**Comment by dechkovanen** [comment]
I could swear the config info was wrong in the wiki an hour ago because I double-checked it. But LowerLeft works, and wiki shows correct information as well, this one is case closed then.

**Comment by almenscorner** [comment]
I just updated :D I will close this
