### ISSUE TITLE
Request: App-Auto-Patch & MAS integration

### ISSUE THREAD

**Issue by BenStreet365** [macadmins/SupportCompanion#65]
Include functionality to include functionality from [App-Auto-Patch](https://github.com/App-Auto-Patch/App-Auto-Patch) and [MAS](https://github.com/mas-cli/mas).

This would be a huge benefit, helping clients continue to keep their end user applications updated :)

**Comment by almenscorner** [comment]
If there is a command or script that could be run for this already, you can setup a custom action which will be a button the user can click in either the tray menu or self service section in the app. For example, in the screen shot, the 6 buttons at the bottom are custom actions I have configured,
```xml
<dict>
    <key>Command</key>
    <string>killall pboard</string>
    <key>Description</key>
    <string>Restarts pasteborad, useful if copy&amp;Paste is not working.</string>
    <key>Icon</key>
    <string>document.on.document.fill</string>
    <key>Name</key>
    <string>Restart clipboard</string>
</dict>
```
<img width="508" alt="image" src="https://github.com/user-attachments/assets/1602276e-92d8-4924-b0d9-1a373f730643" />

**Comment by almenscorner** [comment]
Maybe combine the two is the best case? Run the task on a schedule from Intune and make the action available in SC for the user to run on-demand when needed. It would be possible to setup so actions can be triggered via the CLI and have some LaunchD run it but at that point it's easier to just schedule from Intune

**Comment by BenStreet365** [comment]
Sounds good, thanks again!

**Comment by almenscorner** [comment]
I will add in 2.2.0 the option to trigger actions together with a bunch of other things via the CLI so if you want to setup a schedule to trigger SC you can do that :) 

![image](https://github.com/user-attachments/assets/10b96b05-c473-463e-9d86-a1af50fb05ba)

**Comment by BenStreet365** [comment]
Amazing! Thank you

**Comment by almenscorner** [comment]
It's available for testing in the latest pre-release :)
